name: Selim Çakar
description: "Software Test Engineer, Quality Assurance Analyst, Drummer"
url: https://selimcakar.github.io

linkedin_username: selimcakar
instagram_username:  selimcaakar
twitter_username: selimcaakar
email: selimcakar.tr@gmail.com

avatar: yes
avatar_img_path: "imgs/cv.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/icon.png"

markdown: kramdown
permalink: pretty
